version: '3.3'

services:

  elasticsearch:
    build: .docker/elasticsearch/
    volumes:
      - .docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es_data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    build: .docker/kibana/
    volumes:
      - .docker/kibana/config/:/usr/share/kibana/config:ro
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .docker/nginx/htpasswd:/etc/nginx/htpasswd:ro
    ports:
      - "9200:9200"
      - "9300:9300"
      - "5601:5601"
    depends_on:
      - elasticsearch
      - kibana

volumes:
  es_data:
